server:
  port: 9000

spring:
  application:
    name: auth-BE

  profiles:
    group:
      local: local, jwt, oauth
      alpha: alpha, jwt, oauth
      prod: prod, jwt, oauth
    active: alpha

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:authdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    time-zone: UTC

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: ${SWAGGER_PATH}

app:
  time:
    default-zone: ${APP_DEFAULT_ZONE:Asia/Seoul}
  cookie:
    domain: ${APP_COOKIE_DOMAIN:localhost}
